amcl:
  ros__parameters:
    use_sim_time: false
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    min_particles: 500
    max_particles: 2000
    z_hit: 0.5
    z_short: 0.05
    z_max: 0.05
    z_rand: 0.5
    laser_model_type: "likelihood_field"
    odom_frame_id: "robot1/odom"
    base_frame_id: "robot1/base_link"
    global_frame_id: "robot1/map"
    scan_topic: "scan"

map_server:
  ros__parameters:
    use_sim_time: false
    yaml_filename: "/home/rokey/parking_ws/maps/_map_name_.yaml"

planner_server:
  ros__parameters:
    expected_planner_frequency: 10.0
    use_sim_time: false

controller_server:
  ros__parameters:
    use_sim_time: false
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      debug_trajectory_details: false

bt_navigator:
  ros__parameters:
    use_sim_time: false
    global_frame: "robot1/map"
    robot_base_frame: "robot1/base_link"
    transform_tolerance: 0.5

local_costmap:
  ros__parameters:
    use_sim_time: false
    global_frame: "robot1/odom"
    robot_base_frame: "robot1/base_link"
    publish_frequency: 5.0
    rolling_window: true
    width: 3.0
    height: 3.0
    resolution: 0.05

global_costmap:
  ros__parameters:
    use_sim_time: false
    global_frame: "robot1/map"
    robot_base_frame: "robot1/base_link"
    update_frequency: 1.0
    publish_frequency: 1.0
    resolution: 0.05

